export interface EmojiGroup {
  emoji: string;
  group: string;
}

const EMOJI_GROUP = {
  smileys: "Uśmiechy i emocje",
  people: "Ludzie i ciało",
  symbols: "Ludzie i ciało",
  activity: "Aktywności",
  food: "Jedzenie i napoje",
  animals: "Zwierzęta i natura",
  travel: "Podróże i miejsca",
  objects: "Przedmioty",
  flags: "Flagi",
};

export const ALL_EMOJIS: EmojiGroup[] = [
  // Uśmiechy i emocje
  { emoji: "😀", group: EMOJI_GROUP.smileys },
  { emoji: "😁", group: EMOJI_GROUP.smileys },
  { emoji: "😂", group: EMOJI_GROUP.smileys },
  { emoji: "🤣", group: EMOJI_GROUP.smileys },
  { emoji: "😄", group: EMOJI_GROUP.smileys },
  { emoji: "😅", group: EMOJI_GROUP.smileys },
  { emoji: "😇", group: EMOJI_GROUP.smileys },
  { emoji: "😍", group: EMOJI_GROUP.smileys },
  { emoji: "🥰", group: EMOJI_GROUP.smileys },
  { emoji: "🤩", group: EMOJI_GROUP.smileys },
  { emoji: "😎", group: EMOJI_GROUP.smileys },
  { emoji: "🥳", group: EMOJI_GROUP.smileys },
  { emoji: "😏", group: EMOJI_GROUP.smileys },
  { emoji: "🙃", group: EMOJI_GROUP.smileys },
  { emoji: "🫠", group: EMOJI_GROUP.smileys },
  { emoji: "😜", group: EMOJI_GROUP.smileys },
  { emoji: "🤪", group: EMOJI_GROUP.smileys },
  { emoji: "😮", group: EMOJI_GROUP.smileys },
  { emoji: "😯", group: EMOJI_GROUP.smileys },
  { emoji: "🫡", group: EMOJI_GROUP.smileys },
  { emoji: "🫢", group: EMOJI_GROUP.smileys },
  { emoji: "🫣", group: EMOJI_GROUP.smileys },
  { emoji: "🤯", group: EMOJI_GROUP.smileys },
  { emoji: "😱", group: EMOJI_GROUP.smileys },
  { emoji: "😤", group: EMOJI_GROUP.smileys },
  { emoji: "😡", group: EMOJI_GROUP.smileys },
  { emoji: "😬", group: EMOJI_GROUP.smileys },
  { emoji: "😵", group: EMOJI_GROUP.smileys },
  { emoji: "🫥", group: EMOJI_GROUP.smileys },
  { emoji: "🥹", group: EMOJI_GROUP.smileys },
  { emoji: "😢", group: EMOJI_GROUP.smileys },
  { emoji: "😭", group: EMOJI_GROUP.smileys },
  { emoji: "🤔", group: EMOJI_GROUP.smileys },
  { emoji: "🤨", group: EMOJI_GROUP.smileys },
  { emoji: "🧐", group: EMOJI_GROUP.smileys },
  { emoji: "😴", group: EMOJI_GROUP.smileys },
  { emoji: "🥵", group: EMOJI_GROUP.smileys },
  { emoji: "🥶", group: EMOJI_GROUP.smileys },
  { emoji: "🤡", group: EMOJI_GROUP.smileys },
  { emoji: "👻", group: EMOJI_GROUP.smileys },
  { emoji: "💀", group: EMOJI_GROUP.smileys },
  { emoji: "💩", group: EMOJI_GROUP.smileys },

  // Ludzie i ciało
  { emoji: "🤦", group: EMOJI_GROUP.people },
  { emoji: "👀", group: EMOJI_GROUP.people },
  { emoji: "💪", group: EMOJI_GROUP.people },
  { emoji: "🤞", group: EMOJI_GROUP.people },
  { emoji: "👏", group: EMOJI_GROUP.people },
  { emoji: "🙌", group: EMOJI_GROUP.people },
  { emoji: "🤝", group: EMOJI_GROUP.people },
  { emoji: "🙏", group: EMOJI_GROUP.people },

  // Symbole
  { emoji: "❤️", group: EMOJI_GROUP.symbols },
  { emoji: "💚", group: EMOJI_GROUP.symbols },
  { emoji: "💔", group: EMOJI_GROUP.symbols },
  { emoji: "🫶", group: EMOJI_GROUP.symbols },
  { emoji: "✅", group: EMOJI_GROUP.symbols },
  { emoji: "❌", group: EMOJI_GROUP.symbols },
  { emoji: "🔥", group: EMOJI_GROUP.symbols },
  { emoji: "✨", group: EMOJI_GROUP.symbols },
  { emoji: "💥", group: EMOJI_GROUP.symbols },
  { emoji: "⚡", group: EMOJI_GROUP.symbols },
  { emoji: "🌪️", group: EMOJI_GROUP.symbols },

  // Aktywności
  { emoji: "🏆", group: EMOJI_GROUP.activity },
  { emoji: "🎉", group: EMOJI_GROUP.activity },
  { emoji: "🎊", group: EMOJI_GROUP.activity },
  { emoji: "⚽", group: EMOJI_GROUP.activity },
  { emoji: "🏀", group: EMOJI_GROUP.activity },
  { emoji: "🎾", group: EMOJI_GROUP.activity },
  { emoji: "🏐", group: EMOJI_GROUP.activity },
  { emoji: "🏈", group: EMOJI_GROUP.activity },

  // Jedzenie i napoje
  { emoji: "🍿", group: EMOJI_GROUP.food },
  { emoji: "🍎", group: EMOJI_GROUP.food },
  { emoji: "🍊", group: EMOJI_GROUP.food },
  { emoji: "🍋", group: EMOJI_GROUP.food },
  { emoji: "🍌", group: EMOJI_GROUP.food },
  { emoji: "🍉", group: EMOJI_GROUP.food },
  { emoji: "🍇", group: EMOJI_GROUP.food },
  { emoji: "🍓", group: EMOJI_GROUP.food },
  { emoji: "🍕", group: EMOJI_GROUP.food },
  { emoji: "🍔", group: EMOJI_GROUP.food },
  { emoji: "🍟", group: EMOJI_GROUP.food },
  { emoji: "🌮", group: EMOJI_GROUP.food },
  { emoji: "🌯", group: EMOJI_GROUP.food },
  { emoji: "🥗", group: EMOJI_GROUP.food },
  { emoji: "🍜", group: EMOJI_GROUP.food },
  { emoji: "🍝", group: EMOJI_GROUP.food },
  { emoji: "🍣", group: EMOJI_GROUP.food },
  { emoji: "🍤", group: EMOJI_GROUP.food },
  { emoji: "🍰", group: EMOJI_GROUP.food },
  { emoji: "🎂", group: EMOJI_GROUP.food },
  { emoji: "🍪", group: EMOJI_GROUP.food },
  { emoji: "🍩", group: EMOJI_GROUP.food },
  { emoji: "☕", group: EMOJI_GROUP.food },
  { emoji: "🍵", group: EMOJI_GROUP.food },
  { emoji: "🍶", group: EMOJI_GROUP.food },
  { emoji: "🍺", group: EMOJI_GROUP.food },
  { emoji: "🍻", group: EMOJI_GROUP.food },
  { emoji: "🥂", group: EMOJI_GROUP.food },

  // Zwierzęta i natura
  { emoji: "🐶", group: EMOJI_GROUP.animals },
  { emoji: "🐱", group: EMOJI_GROUP.animals },
  { emoji: "🐭", group: EMOJI_GROUP.animals },
  { emoji: "🐹", group: EMOJI_GROUP.animals },
  { emoji: "🐰", group: EMOJI_GROUP.animals },
  { emoji: "🦊", group: EMOJI_GROUP.animals },
  { emoji: "🐻", group: EMOJI_GROUP.animals },
  { emoji: "🐼", group: EMOJI_GROUP.animals },
  { emoji: "🐨", group: EMOJI_GROUP.animals },
  { emoji: "🐯", group: EMOJI_GROUP.animals },
  { emoji: "🦁", group: EMOJI_GROUP.animals },
  { emoji: "🐮", group: EMOJI_GROUP.animals },
  { emoji: "🐷", group: EMOJI_GROUP.animals },
  { emoji: "🐸", group: EMOJI_GROUP.animals },
  { emoji: "🐵", group: EMOJI_GROUP.animals },
  { emoji: "🐐", group: EMOJI_GROUP.animals },
  { emoji: "🦅", group: EMOJI_GROUP.animals },
  { emoji: "🦆", group: EMOJI_GROUP.animals },
  { emoji: "🦉", group: EMOJI_GROUP.animals },
  { emoji: "🦇", group: EMOJI_GROUP.animals },
  { emoji: "🐢", group: EMOJI_GROUP.animals },
  { emoji: "🐍", group: EMOJI_GROUP.animals },
  { emoji: "🐙", group: EMOJI_GROUP.animals },
  { emoji: "🦑", group: EMOJI_GROUP.animals },
  { emoji: "🦐", group: EMOJI_GROUP.animals },
  { emoji: "🦞", group: EMOJI_GROUP.animals },
  { emoji: "🦀", group: EMOJI_GROUP.animals },
  { emoji: "🐡", group: EMOJI_GROUP.animals },
  { emoji: "🐠", group: EMOJI_GROUP.animals },
  { emoji: "🐟", group: EMOJI_GROUP.animals },
  { emoji: "🐬", group: EMOJI_GROUP.animals },
  { emoji: "🐳", group: EMOJI_GROUP.animals },
  { emoji: "🌳", group: EMOJI_GROUP.animals },
  { emoji: "🌲", group: EMOJI_GROUP.animals },
  { emoji: "🌴", group: EMOJI_GROUP.animals },
  { emoji: "🌵", group: EMOJI_GROUP.animals },
  { emoji: "🌾", group: EMOJI_GROUP.animals },
  { emoji: "💐", group: EMOJI_GROUP.animals },
  { emoji: "🌸", group: EMOJI_GROUP.animals },
  { emoji: "🌺", group: EMOJI_GROUP.animals },
  { emoji: "🌻", group: EMOJI_GROUP.animals },
  { emoji: "🌼", group: EMOJI_GROUP.animals },
  { emoji: "🌞", group: EMOJI_GROUP.animals },
  { emoji: "⭐", group: EMOJI_GROUP.animals },

  // Podróże i miejsca
  { emoji: "🚀", group: EMOJI_GROUP.travel },
  { emoji: "🚁", group: EMOJI_GROUP.travel },
  { emoji: "🚂", group: EMOJI_GROUP.travel },
  { emoji: "🚃", group: EMOJI_GROUP.travel },
  { emoji: "🚄", group: EMOJI_GROUP.travel },
  { emoji: "🚅", group: EMOJI_GROUP.travel },
  { emoji: "🚆", group: EMOJI_GROUP.travel },
  { emoji: "🚇", group: EMOJI_GROUP.travel },
  { emoji: "🚈", group: EMOJI_GROUP.travel },
  { emoji: "🚉", group: EMOJI_GROUP.travel },
  { emoji: "🚊", group: EMOJI_GROUP.travel },
  { emoji: "🚝", group: EMOJI_GROUP.travel },
  { emoji: "🚞", group: EMOJI_GROUP.travel },
  { emoji: "🚋", group: EMOJI_GROUP.travel },
  { emoji: "🚌", group: EMOJI_GROUP.travel },
  { emoji: "🚍", group: EMOJI_GROUP.travel },
  { emoji: "🚎", group: EMOJI_GROUP.travel },
  { emoji: "🚐", group: EMOJI_GROUP.travel },
  { emoji: "🚑", group: EMOJI_GROUP.travel },
  { emoji: "🚒", group: EMOJI_GROUP.travel },
  { emoji: "🚓", group: EMOJI_GROUP.travel },
  { emoji: "🚔", group: EMOJI_GROUP.travel },
  { emoji: "🚕", group: EMOJI_GROUP.travel },
  { emoji: "🚖", group: EMOJI_GROUP.travel },
  { emoji: "🚗", group: EMOJI_GROUP.travel },
  { emoji: "🚘", group: EMOJI_GROUP.travel },
  { emoji: "🚙", group: EMOJI_GROUP.travel },
  { emoji: "🚚", group: EMOJI_GROUP.travel },
  { emoji: "🚛", group: EMOJI_GROUP.travel },
  { emoji: "🚜", group: EMOJI_GROUP.travel },
  { emoji: "⛵", group: EMOJI_GROUP.travel },
  { emoji: "🛶", group: EMOJI_GROUP.travel },
  { emoji: "⛴", group: EMOJI_GROUP.travel },
  { emoji: "🛳", group: EMOJI_GROUP.travel },
  { emoji: "⛵", group: EMOJI_GROUP.travel },
  { emoji: "🛩", group: EMOJI_GROUP.travel },
  { emoji: "✈️", group: EMOJI_GROUP.travel },
  { emoji: "🛫", group: EMOJI_GROUP.travel },
  { emoji: "🛬", group: EMOJI_GROUP.travel },
  { emoji: "🏠", group: EMOJI_GROUP.travel },
  { emoji: "🏡", group: EMOJI_GROUP.travel },
  { emoji: "🏢", group: EMOJI_GROUP.travel },
  { emoji: "🏬", group: EMOJI_GROUP.travel },
  { emoji: "🏭", group: EMOJI_GROUP.travel },
  { emoji: "🏯", group: EMOJI_GROUP.travel },
  { emoji: "🏰", group: EMOJI_GROUP.travel },

  // Przedmioty
  { emoji: "📱", group: EMOJI_GROUP.objects },
  { emoji: "💻", group: EMOJI_GROUP.objects },
  { emoji: "⌨️", group: EMOJI_GROUP.objects },
  { emoji: "🖱", group: EMOJI_GROUP.objects },
  { emoji: "🖨", group: EMOJI_GROUP.objects },
  { emoji: "🖥", group: EMOJI_GROUP.objects },
  { emoji: "🎮", group: EMOJI_GROUP.objects },
  { emoji: "🎯", group: EMOJI_GROUP.objects },
  { emoji: "🎲", group: EMOJI_GROUP.objects },
  { emoji: "🎳", group: EMOJI_GROUP.objects },
  { emoji: "🎨", group: EMOJI_GROUP.objects },
  { emoji: "🎭", group: EMOJI_GROUP.objects },
  { emoji: "🎬", group: EMOJI_GROUP.objects },
  { emoji: "🎤", group: EMOJI_GROUP.objects },
  { emoji: "🎧", group: EMOJI_GROUP.objects },
  { emoji: "🎼", group: EMOJI_GROUP.objects },
  { emoji: "🎹", group: EMOJI_GROUP.objects },
  { emoji: "🎸", group: EMOJI_GROUP.objects },
  { emoji: "🎺", group: EMOJI_GROUP.objects },
  { emoji: "🎷", group: EMOJI_GROUP.objects },
  { emoji: "⌚", group: EMOJI_GROUP.objects },
  { emoji: "📖", group: EMOJI_GROUP.objects },
  { emoji: "📚", group: EMOJI_GROUP.objects },
  { emoji: "📝", group: EMOJI_GROUP.objects },
  { emoji: "✏️", group: EMOJI_GROUP.objects },
  { emoji: "📏", group: EMOJI_GROUP.objects },
  { emoji: "📌", group: EMOJI_GROUP.objects },
  { emoji: "📍", group: EMOJI_GROUP.objects },
  { emoji: "📎", group: EMOJI_GROUP.objects },
  { emoji: "📐", group: EMOJI_GROUP.objects },
  { emoji: "🎓", group: EMOJI_GROUP.objects },
  { emoji: "💎", group: EMOJI_GROUP.objects },
  { emoji: "🔧", group: EMOJI_GROUP.objects },
  { emoji: "🔨", group: EMOJI_GROUP.objects },
  { emoji: "⛏", group: EMOJI_GROUP.objects },
  { emoji: "🔩", group: EMOJI_GROUP.objects },
  { emoji: "⚙️", group: EMOJI_GROUP.objects },
  { emoji: "🧱", group: EMOJI_GROUP.objects },
  { emoji: "⛓", group: EMOJI_GROUP.objects },
  { emoji: "🧲", group: EMOJI_GROUP.objects },
  { emoji: "🔫", group: EMOJI_GROUP.objects },
  { emoji: "💣", group: EMOJI_GROUP.objects },
  { emoji: "🔪", group: EMOJI_GROUP.objects },
  { emoji: "🗡", group: EMOJI_GROUP.objects },
  { emoji: "🛡", group: EMOJI_GROUP.objects },
  { emoji: "🚬", group: EMOJI_GROUP.objects },
  { emoji: "⚰️", group: EMOJI_GROUP.objects },
  { emoji: "⚱️", group: EMOJI_GROUP.objects },
  { emoji: "🏺", group: EMOJI_GROUP.objects },
  { emoji: "💈", group: EMOJI_GROUP.objects },
  { emoji: "⚗️", group: EMOJI_GROUP.objects },
  { emoji: "🔭", group: EMOJI_GROUP.objects },
  { emoji: "🔬", group: EMOJI_GROUP.objects },
  { emoji: "🕯", group: EMOJI_GROUP.objects },
  { emoji: "💡", group: EMOJI_GROUP.objects },
  { emoji: "🔦", group: EMOJI_GROUP.objects },
  { emoji: "🏮", group: EMOJI_GROUP.objects },
  { emoji: "🪜", group: EMOJI_GROUP.objects },
  { emoji: "📔", group: EMOJI_GROUP.objects },
  { emoji: "📕", group: EMOJI_GROUP.objects },
  { emoji: "📖", group: EMOJI_GROUP.objects },
  { emoji: "📗", group: EMOJI_GROUP.objects },
  { emoji: "📘", group: EMOJI_GROUP.objects },
  { emoji: "📙", group: EMOJI_GROUP.objects },
  { emoji: "📚", group: EMOJI_GROUP.objects },
  { emoji: "📓", group: EMOJI_GROUP.objects },
  { emoji: "📒", group: EMOJI_GROUP.objects },
  { emoji: "📃", group: EMOJI_GROUP.objects },
  { emoji: "📜", group: EMOJI_GROUP.objects },
  { emoji: "📄", group: EMOJI_GROUP.objects },
  { emoji: "📰", group: EMOJI_GROUP.objects },
  { emoji: "🗞", group: EMOJI_GROUP.objects },

  // Flagi
  { emoji: "🇦🇨", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇩", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇫", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇮", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇱", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇴", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇶", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇸", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇹", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇺", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇼", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇽", group: EMOJI_GROUP.flags },
  { emoji: "🇦🇿", group: EMOJI_GROUP.flags },

  { emoji: "🇧🇦", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇧", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇩", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇫", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇭", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇮", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇯", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇱", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇳", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇴", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇶", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇸", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇹", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇻", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇼", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇾", group: EMOJI_GROUP.flags },
  { emoji: "🇧🇿", group: EMOJI_GROUP.flags },

  { emoji: "🇨🇦", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇨", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇩", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇫", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇭", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇮", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇰", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇱", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇳", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇴", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇵", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇶", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇺", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇻", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇼", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇽", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇾", group: EMOJI_GROUP.flags },
  { emoji: "🇨🇿", group: EMOJI_GROUP.flags },

  { emoji: "🇩🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇩🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇩🇯", group: EMOJI_GROUP.flags },
  { emoji: "🇩🇰", group: EMOJI_GROUP.flags },
  { emoji: "🇩🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇩🇴", group: EMOJI_GROUP.flags },
  { emoji: "🇩🇿", group: EMOJI_GROUP.flags },

  { emoji: "🇪🇦", group: EMOJI_GROUP.flags },
  { emoji: "🇪🇨", group: EMOJI_GROUP.flags },
  { emoji: "🇪🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇪🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇪🇭", group: EMOJI_GROUP.flags },
  { emoji: "🇪🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇪🇸", group: EMOJI_GROUP.flags },
  { emoji: "🇪🇹", group: EMOJI_GROUP.flags },
  { emoji: "🇪🇺", group: EMOJI_GROUP.flags },

  { emoji: "🇫🇮", group: EMOJI_GROUP.flags },
  { emoji: "🇫🇯", group: EMOJI_GROUP.flags },
  { emoji: "🇫🇰", group: EMOJI_GROUP.flags },
  { emoji: "🇫🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇫🇴", group: EMOJI_GROUP.flags },
  { emoji: "🇫🇷", group: EMOJI_GROUP.flags },

  { emoji: "🇬🇦", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇧", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇩", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇫", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇭", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇮", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇱", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇳", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇵", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇶", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇸", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇹", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇺", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇼", group: EMOJI_GROUP.flags },
  { emoji: "🇬🇾", group: EMOJI_GROUP.flags },

  { emoji: "🇭🇰", group: EMOJI_GROUP.flags },
  { emoji: "🇭🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇭🇳", group: EMOJI_GROUP.flags },
  { emoji: "🇭🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇭🇹", group: EMOJI_GROUP.flags },
  { emoji: "🇭🇺", group: EMOJI_GROUP.flags },

  { emoji: "🇮🇨", group: EMOJI_GROUP.flags },
  { emoji: "🇮🇩", group: EMOJI_GROUP.flags },
  { emoji: "🇮🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇮🇱", group: EMOJI_GROUP.flags },
  { emoji: "🇮🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇮🇳", group: EMOJI_GROUP.flags },
  { emoji: "🇮🇴", group: EMOJI_GROUP.flags },
  { emoji: "🇮🇶", group: EMOJI_GROUP.flags },
  { emoji: "🇮🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇮🇸", group: EMOJI_GROUP.flags },
  { emoji: "🇮🇹", group: EMOJI_GROUP.flags },

  { emoji: "🇯🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇯🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇯🇴", group: EMOJI_GROUP.flags },
  { emoji: "🇯🇵", group: EMOJI_GROUP.flags },

  { emoji: "🇰🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇰🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇰🇭", group: EMOJI_GROUP.flags },
  { emoji: "🇰🇮", group: EMOJI_GROUP.flags },
  { emoji: "🇰🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇰🇳", group: EMOJI_GROUP.flags },
  { emoji: "🇰🇵", group: EMOJI_GROUP.flags },
  { emoji: "🇰🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇰🇼", group: EMOJI_GROUP.flags },
  { emoji: "🇰🇾", group: EMOJI_GROUP.flags },
  { emoji: "🇰🇿", group: EMOJI_GROUP.flags },

  { emoji: "🇱🇦", group: EMOJI_GROUP.flags },
  { emoji: "🇱🇧", group: EMOJI_GROUP.flags },
  { emoji: "🇱🇨", group: EMOJI_GROUP.flags },
  { emoji: "🇱🇮", group: EMOJI_GROUP.flags },
  { emoji: "🇱🇰", group: EMOJI_GROUP.flags },
  { emoji: "🇱🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇱🇸", group: EMOJI_GROUP.flags },
  { emoji: "🇱🇹", group: EMOJI_GROUP.flags },
  { emoji: "🇱🇺", group: EMOJI_GROUP.flags },
  { emoji: "🇱🇻", group: EMOJI_GROUP.flags },
  { emoji: "🇱🇾", group: EMOJI_GROUP.flags },

  { emoji: "🇲🇦", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇨", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇩", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇫", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇭", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇰", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇱", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇳", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇴", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇵", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇶", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇸", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇹", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇺", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇻", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇼", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇽", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇾", group: EMOJI_GROUP.flags },
  { emoji: "🇲🇿", group: EMOJI_GROUP.flags },

  { emoji: "🇳🇦", group: EMOJI_GROUP.flags },
  { emoji: "🇳🇨", group: EMOJI_GROUP.flags },
  { emoji: "🇳🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇳🇫", group: EMOJI_GROUP.flags },
  { emoji: "🇳🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇳🇮", group: EMOJI_GROUP.flags },
  { emoji: "🇳🇱", group: EMOJI_GROUP.flags },
  { emoji: "🇳🇴", group: EMOJI_GROUP.flags },
  { emoji: "🇳🇵", group: EMOJI_GROUP.flags },
  { emoji: "🇳🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇳🇺", group: EMOJI_GROUP.flags },
  { emoji: "🇳🇿", group: EMOJI_GROUP.flags },

  { emoji: "🇴🇲", group: EMOJI_GROUP.flags },

  { emoji: "🇵🇦", group: EMOJI_GROUP.flags },
  { emoji: "🇵🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇵🇫", group: EMOJI_GROUP.flags },
  { emoji: "🇵🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇵🇭", group: EMOJI_GROUP.flags },
  { emoji: "🇵🇰", group: EMOJI_GROUP.flags },
  { emoji: "🇵🇱", group: EMOJI_GROUP.flags },
  { emoji: "🇵🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇵🇳", group: EMOJI_GROUP.flags },
  { emoji: "🇵🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇵🇸", group: EMOJI_GROUP.flags },
  { emoji: "🇵🇹", group: EMOJI_GROUP.flags },
  { emoji: "🇵🇼", group: EMOJI_GROUP.flags },
  { emoji: "🇵🇾", group: EMOJI_GROUP.flags },

  { emoji: "🇶🇦", group: EMOJI_GROUP.flags },

  { emoji: "🇷🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇷🇴", group: EMOJI_GROUP.flags },
  { emoji: "🇷🇸", group: EMOJI_GROUP.flags },
  { emoji: "🇷🇺", group: EMOJI_GROUP.flags },
  { emoji: "🇷🇼", group: EMOJI_GROUP.flags },

  { emoji: "🇸🇦", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇧", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇨", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇩", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇭", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇮", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇯", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇰", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇱", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇳", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇴", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇸", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇹", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇻", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇽", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇾", group: EMOJI_GROUP.flags },
  { emoji: "🇸🇿", group: EMOJI_GROUP.flags },

  { emoji: "🇹🇦", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇨", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇩", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇫", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇭", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇯", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇰", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇱", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇳", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇴", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇷", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇹", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇻", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇼", group: EMOJI_GROUP.flags },
  { emoji: "🇹🇿", group: EMOJI_GROUP.flags },

  { emoji: "🇺🇦", group: EMOJI_GROUP.flags },
  { emoji: "🇺🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇺🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇺🇳", group: EMOJI_GROUP.flags },
  { emoji: "🇺🇸", group: EMOJI_GROUP.flags },
  { emoji: "🇺🇾", group: EMOJI_GROUP.flags },
  { emoji: "🇺🇿", group: EMOJI_GROUP.flags },

  { emoji: "🇻🇦", group: EMOJI_GROUP.flags },
  { emoji: "🇻🇨", group: EMOJI_GROUP.flags },
  { emoji: "🇻🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇻🇬", group: EMOJI_GROUP.flags },
  { emoji: "🇻🇮", group: EMOJI_GROUP.flags },
  { emoji: "🇻🇳", group: EMOJI_GROUP.flags },
  { emoji: "🇻🇺", group: EMOJI_GROUP.flags },

  { emoji: "🇼🇫", group: EMOJI_GROUP.flags },
  { emoji: "🇼🇸", group: EMOJI_GROUP.flags },

  { emoji: "🇽🇰", group: EMOJI_GROUP.flags },

  { emoji: "🇾🇪", group: EMOJI_GROUP.flags },
  { emoji: "🇾🇹", group: EMOJI_GROUP.flags },

  { emoji: "🇿🇦", group: EMOJI_GROUP.flags },
  { emoji: "🇿🇲", group: EMOJI_GROUP.flags },
  { emoji: "🇿🇼", group: EMOJI_GROUP.flags },
];
